### ISSUE TITLE
Micro-simulation RuntimeError: Factor is exactly singular

### ISSUE THREAD

**Issue by HelenaKschidock** [HelenaKschidock/macro-micro#41]
This occurred in the micro-sim while running the coupled asymmetric case without mpi on the server, after 20 timesteps: 

```Traceback (most recent call last):
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/matrix/_base.py", line 320, in getprecon
    precon_object = precon_method(**precon_args)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/matrix/_scipy.py", line 91, in _precon_direct
    return scipy.sparse.linalg.factorized(self.core.tocsc())
  File "/usr/lib/python3/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 443, in factorized
    return splu(A).solve
  File "/usr/lib/python3/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 310, in splu
    return _superlu.gstrf(N, A.nnz, A.data, A.indices, A.indptr,
RuntimeError: Factor is exactly singular

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run-micro-problems.py", line 11, in <module>
    manager.solve()
  File "/home/kschidha/.local/lib/python3.8/site-packages/micro_manager/micro_manager.py", line 347, in solve
    micro_sims_output = self.solve_micro_simulations(micro_sims_input)
  File "/home/kschidha/.local/lib/python3.8/site-packages/micro_manager/micro_manager.py", line 322, in solve_micro_simulations
    micro_sims_output.append(self._micro_sims[i].solve(micro_sims_input[i], self._dt))
  File "/home/kschidha/dumux/dumux-adapter/build-cmake/examples/macro-micro/python-micro-heat/micro_heat.py", line 242, in solve
    solu = self._solve_heat_cell_problem(topo, solphi)
  File "/home/kschidha/dumux/dumux-adapter/build-cmake/examples/macro-micro/python-micro-heat/micro_heat.py", line 220, in _solve_heat_cell_problem
    u_coeffs = solver.solve_linear('solu', res, constrain=self._ucons, arguments=args)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/solver.py", line 77, in wrapper
    return f(*ba.args, **ba.kwargs)[target]
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/types.py", line 59, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/cache.py", line 183, in wrapper
    return func(*args, **kwargs)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/solver.py", line 352, in solve_linear
    vlhs[vmask] -= jac.solve(res, **solveargs)
  File "/home/kschidha/.local/lib/python3.8/site-packages/treelog/__init__.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/matrix/_base.py", line 144, in solve
    return self._solver(rhs, solver, atol=atol, rtol=rtol, **solverargs)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/matrix/_base.py", line 209, in _solver
    lhs = solver_method(rhs, atol=atol, **solverargs)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/matrix/_base.py", line 227, in _solver_arnoldi
    solve = self.getprecon(precon, **args, **preconargs)
  File "/home/kschidha/.local/lib/python3.8/site-packages/nutils/matrix/_base.py", line 324, in getprecon
    raise MatrixError('failed to create preconditioner: {}'.format(e)) from e
nutils.matrix.MatrixError: failed to create preconditioner: Factor is exactly singular
(0) 22:03:05 [impl::SolverInterfaceImpl]:167 in ~SolverInterfaceImpl: Implicitly finalizing in destructor```

**Comment by HelenaKschidock** [comment]
possibly fixed by #51 ?
